package test

/**
 * @File : testProduct.go
 * @Description : 产品相关功能测试
 * @Author : chen
 * @Date : 2023/12/27
 */

import (
	"onlineshop/models"
	"onlineshop/service"
)

var testProduct = []models.Product{
	{
		StoreId:       1,
		ProductName:   "白鞋",
		Description:   "这是白鞋",
		ProductStatus: 1,
		MonthNum:      100,
		Stock:         200,
		ProductType:   1,
		Likes:         1200,
		Comments:      100,
		Price:         100,
	},
	{
		StoreId:       1,
		ProductName:   "黑鞋",
		Description:   "这是黑鞋",
		ProductStatus: 1,
		MonthNum:      200,
		Stock:         300,
		ProductType:   1,
		Likes:         1400,
		Comments:      200,
		Price:         200,
	},
	{
		StoreId:       1,
		ProductName:   "蓝鞋",
		Description:   "这是蓝鞋",
		ProductStatus: 1,
		MonthNum:      300,
		Stock:         400,
		ProductType:   1,
		Likes:         1500,
		Comments:      300,
		Price:         300,
	},
	{
		StoreId:       1,
		ProductName:   "绿鞋",
		Description:   "这是绿鞋",
		ProductStatus: 1,
		MonthNum:      400,
		Stock:         500,
		ProductType:   1,
		Likes:         1600,
		Comments:      400,
		Price:         400,
	},
	// 5
	{
		StoreId:       1,
		ProductName:   "白衣服",
		Description:   "这是白衣服",
		ProductStatus: 1,
		MonthNum:      100,
		Stock:         200,
		ProductType:   1,
		Likes:         1200,
		Comments:      100,
		Price:         100,
	},
	{
		StoreId:       1,
		ProductName:   "黑衣服",
		Description:   "这是黑衣服",
		ProductStatus: 1,
		MonthNum:      200,
		Stock:         300,
		ProductType:   1,
		Likes:         1400,
		Comments:      200,
		Price:         200,
	},
	{
		StoreId:       1,
		ProductName:   "蓝衣服",
		Description:   "这是蓝衣服",
		ProductStatus: 1,
		MonthNum:      300,
		Stock:         400,
		ProductType:   1,
		Likes:         1500,
		Comments:      300,
		Price:         300,
	},
	{
		StoreId:       1,
		ProductName:   "绿衣服",
		Description:   "这是绿衣服",
		ProductStatus: 1,
		MonthNum:      400,
		Stock:         500,
		ProductType:   1,
		Likes:         1600,
		Comments:      400,
		Price:         400,
	},
	// 9
	{
		StoreId:       1,
		ProductName:   "白裤子",
		Description:   "这是白裤子",
		ProductStatus: 1,
		MonthNum:      100,
		Stock:         200,
		ProductType:   1,
		Likes:         1200,
		Comments:      100,
		Price:         100,
	},
	{
		StoreId:       1,
		ProductName:   "黑裤子",
		Description:   "这是黑裤子",
		ProductStatus: 1,
		MonthNum:      200,
		Stock:         300,
		ProductType:   1,
		Likes:         1400,
		Comments:      200,
		Price:         200,
	},
	{
		StoreId:       1,
		ProductName:   "蓝裤子",
		Description:   "这是蓝裤子",
		ProductStatus: 1,
		MonthNum:      300,
		Stock:         400,
		ProductType:   1,
		Likes:         1500,
		Comments:      300,
		Price:         300,
	},
	{
		StoreId:       1,
		ProductName:   "绿裤子",
		Description:   "这是绿裤子",
		ProductStatus: 1,
		MonthNum:      400,
		Stock:         500,
		ProductType:   1,
		Likes:         1600,
		Comments:      400,
		Price:         400,
	},
	// 13
	{
		StoreId:       1,
		ProductName:   "白帽子",
		Description:   "这是白帽子",
		ProductStatus: 1,
		MonthNum:      100,
		Stock:         200,
		ProductType:   1,
		Likes:         1200,
		Comments:      100,
		Price:         100,
	},
	{
		StoreId:       1,
		ProductName:   "黑帽子",
		Description:   "这是黑帽子",
		ProductStatus: 1,
		MonthNum:      200,
		Stock:         300,
		ProductType:   1,
		Likes:         1400,
		Comments:      200,
		Price:         200,
	},
	{
		StoreId:       1,
		ProductName:   "蓝帽子",
		Description:   "这是蓝帽子",
		ProductStatus: 1,
		MonthNum:      300,
		Stock:         400,
		ProductType:   1,
		Likes:         1500,
		Comments:      300,
		Price:         300,
	},
	{
		StoreId:       1,
		ProductName:   "绿帽子",
		Description:   "这是绿帽子",
		ProductStatus: 1,
		MonthNum:      400,
		Stock:         500,
		ProductType:   1,
		Likes:         1600,
		Comments:      400,
		Price:         400,
	},
}

func addProduct() {
	for _, i := range testProduct {
		service.AddProduct(&i)
	}
}
